allow_remote_control yes

#appearance
background_opacity 0.7
cursor_shape beam
enable_audio_bell no
enabled_layouts splits,stack,tall

#custom keybindings
#tabs
map ctrl+shift+t new_tab
map ctrl+shift+q close_tab
map ctrl+shift+right next_tab
map ctrl+shift+left previous_tab

#splits
map ctrl+shift+d launch --location=vsplit --cwd=current
map ctrl+shift+s launch --location=hsplit --cwd=current

#windows
map ctrl+shift+h neighboring_window up
map ctrl+shift+j neighboring_window down
map ctrl+shift+k neighboring_window left
map ctrl+shift+l neighboring_window right
map ctrl+shift+w close_window


# BEGIN_KITTY_FONTS
font_family      family='JetBrainsMono Nerd Font Mono' postscript_name=JetBrainsMonoNFM-Regular
bold_font        family='JetBrainsMono Nerd Font Mono' postscript_name=JetBrainsMonoNFM-Bold
italic_font      family='JetBrainsMono Nerd Font Mono' postscript_name=JetBrainsMonoNFM-Italic
bold_italic_font family='JetBrainsMono Nerd Font Mono' postscript_name=JetBrainsMonoNFM-BoldItalic
# END_KITTY_FONTS

font_size 14.0
