tap "felixkratz/formulae"
tap "koekeishiya/formulae"
tap "romkatv/powerlevel10k"

brew "bat"
brew "eza"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "fzf-tab"
brew "gemini-cli"
brew "git"
brew "git-filter-repo"
brew "jq"
brew "neofetch"
brew "neovim", args: ["HEAD"]
brew "onefetch"
brew "ripgrep"
brew "tldr"
brew "tree"
brew "vivid"
brew "watch"
brew "wget"
brew "yazi"
brew "zoxide"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

brew "felixkratz/formulae/sketchybar"
brew "koekeishiya/formulae/yabai"

cask "font-hack-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "kitty"
cask "visual-studio-code"

vscode "anthropic.claude-code"
vscode "catppuccin.catppuccin-vsc"
vscode "coderabbit.coderabbit-vscode"

